name: Build APWorld
on: push

jobs:
  build_apworld:
    name: Build APWorld
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: oprypin/find-latest-tag@v1
      with:
        repository: KScl/TyrianArchipelago
        prefix: v1
      id: aptyrian

    - name: Create APWorld (zip)
      shell: bash
      run: |
        mkdir tyrian
        mkdir tyrian/test
        mkdir tyrian/crossgame
        mkdir tyrian/docs
        cp LICENSE tyrian/
        cp *.py tyrian/
        cp test/*.py tyrian/test/
        cp crossgame/*.py tyrian/crossgame/
        cp docs/*.md tyrian/docs/
        bash .github/manifest.sh ${{ steps.aptyrian.outputs.tag }}
        zip -r ~/tyrian.apworld tyrian archipelago.json

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: apworld
        path: ~/tyrian.apworld
        if-no-files-found: error
        compression-level: 0
