name: Unittests
on: [ push, pull_request ]

jobs:
  unittest:
    name: Run Unittests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Archipelago
      uses: actions/checkout@v4
      with:
        repository: ArchipelagoMW/Archipelago

    - name: Checkout APWorld
      uses: actions/checkout@v4
      with:
        path: worlds/tyrian

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-subtests pytest-xdist mypy ruff
        python ModuleUpdate.py --yes --force
        python Launcher.py --update_settings

    - name: Run pytest (unit tests)
      run: python -m pytest worlds/tyrian -Wignore::DeprecationWarning
    - name: Run ruff (linting)
      run: python -m ruff check --output-format=github worlds/tyrian
    - name: Run mypy (type checking)
      run: python -m mypy worlds/tyrian --follow-imports=silent
